name = "cashapp-generator"
compatibility_date = "2024-12-19"

[env.production]
name = "cashapp-generator"

# Cloudflare Pages configuration
pages_build_output_dir = "."
compatibility_flags = ["nodejs_compat"] 